const allTimezones = [
    { timezone: 'Asia/Jakarta', city: 'Jakarta', region: 'Asia - Indonesia' },
    { timezone: 'Asia/Bangkok', city: 'Bangkok', region: 'Asia - Thailand' },
    { timezone: 'Asia/Singapore', city: 'Singapore', region: 'Asia - Singapore' },
    { timezone: 'Asia/Tokyo', city: 'Tokyo', region: 'Asia - Japan' },
    { timezone: 'Asia/Seoul', city: 'Seoul', region: 'Asia - South Korea' },
    { timezone: 'Asia/Shanghai', city: 'Shanghai', region: 'Asia - China' },
    { timezone: 'Asia/Hong_Kong', city: 'Hong Kong', region: 'Asia - Hong Kong' },
    { timezone: 'Asia/Dubai', city: 'Dubai', region: 'Asia - UAE' },
    { timezone: 'Europe/London', city: 'London', region: 'Europe - UK' },
    { timezone: 'Europe/Paris', city: 'Paris', region: 'Europe - France' },
    { timezone: 'Europe/Berlin', city: 'Berlin', region: 'Europe - Germany' },
    { timezone: 'Europe/Rome', city: 'Rome', region: 'Europe - Italy' },
    { timezone: 'Europe/Moscow', city: 'Moscow', region: 'Europe - Russia' },
    { timezone: 'America/New_York', city: 'New York', region: 'America - USA (EST)' },
    { timezone: 'America/Chicago', city: 'Chicago', region: 'America - USA (CST)' },
    { timezone: 'America/Denver', city: 'Denver', region: 'America - USA (MST)' },
    { timezone: 'America/Los_Angeles', city: 'Los Angeles', region: 'America - USA (PST)' },
    { timezone: 'America/Toronto', city: 'Toronto', region: 'America - Canada' },
    { timezone: 'America/Sao_Paulo', city: 'Sao Paulo', region: 'America - Brazil' },
    { timezone: 'America/Buenos_Aires', city: 'Buenos Aires', region: 'America - Argentina' },
    { timezone: 'Africa/Cairo', city: 'Cairo', region: 'Africa - Egypt' },
    { timezone: 'Africa/Johannesburg', city: 'Johannesburg', region: 'Africa - South Africa' },
    { timezone: 'Africa/Lagos', city: 'Lagos', region: 'Africa - Nigeria' },
    { timezone: 'Australia/Sydney', city: 'Sydney', region: 'Australia - NSW' },
    { timezone: 'Australia/Melbourne', city: 'Melbourne', region: 'Australia - VIC' },
    { timezone: 'Australia/Brisbane', city: 'Brisbane', region: 'Australia - QLD' },
    { timezone: 'Pacific/Auckland', city: 'Auckland', region: 'Oceania - New Zealand' },
    { timezone: 'UTC', city: 'UTC', region: 'UTC' }
];